/**
 * NewsFeed Component - Dynamic News & Analysis Feed
 *
 * Fetches and displays the latest DCI recaps and fantasy analysis
 * generated by the Gemini AI news service.
 */

import React, { useState, useEffect } from 'react';
import {
  Trophy, Flame, Clock, ChevronRight, TrendingUp, TrendingDown,
  Minus, AlertCircle, Newspaper, Loader2, DollarSign, ArrowUpRight, ArrowDownRight
} from 'lucide-react';
import { getRecentNews } from '../../api/functions';

// =============================================================================
// STATIC FALLBACK DATA (Used when API is unavailable or for initial render)
// =============================================================================

const FALLBACK_NEWS = [
  {
    id: 'fallback-1',
    category: 'dci',
    headline: 'Blue Devils +0.425: VP Surge Extends Lead at San Antonio',
    summary: 'BD extends their lead with a commanding 97.850 performance. Their Visual Proficiency jumped 0.35 points, the largest single-show VP gain of the season.',
    fantasyImpact: 'Directors rostering Blue Devils Brass saw +3.8 points (11.2% ROI). Bluecoats percussion emerging as a buy-low opportunity.',
    fantasyMetrics: {
      topROI: { corps: 'Blue Devils', caption: 'Brass', pointsGained: 3.8, roiPercent: 11.2 },
      buyLow: [{ corps: 'Bluecoats', reason: 'Percussion undervalued after drill change', projectedGain: 2.1 }],
      sellHigh: [{ corps: 'Phantom Regiment', reason: 'GE regression likely', riskLevel: 'medium' }],
    },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    trendingCorps: [
      { corps: 'Blue Devils', direction: 'up', reason: 'VP +0.35, largest of season', weeklyChange: 0.425, fantasyValue: 'hold' },
      { corps: 'Bluecoats', direction: 'up', reason: 'Visual Analysis breakout', weeklyChange: 0.31, fantasyValue: 'buy' },
    ],
  },
  {
    id: 'fallback-2',
    category: 'fantasy',
    headline: 'Crown Brass +0.8: The Breakout Caption of Week 4',
    summary: 'Carolina Crown\'s brass section posted 18.7 in Music Analysis, their highest mark since 2019. ROI leaders this week.',
    fantasyImpact: 'Crown Brass delivered +4.2 points (12.3% ROI). SCV Guard up 8.1% ROI. Lock them in if available.',
    fantasyMetrics: {
      topROI: { corps: 'Carolina Crown', caption: 'Brass', pointsGained: 4.2, roiPercent: 12.3 },
      buyLow: [{ corps: 'Cadets', reason: 'New show design underperforming', projectedGain: 1.8 }],
      sellHigh: [],
    },
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    trendingCorps: [
      { corps: 'Carolina Crown', direction: 'up', reason: 'Brass +0.8, best since 2019', weeklyChange: 0.62, fantasyValue: 'buy' },
    ],
  },
  {
    id: 'fallback-3',
    category: 'dci',
    headline: 'Crown Visual +0.45: New Closer Pays Immediate Dividends',
    summary: 'Crown debuts reimagined finale. Visual Proficiency jumped from 18.1 to 18.55, with Color Guard posting season-high 9.4.',
    fantasyImpact: 'Crown Visual captions spiked +2.9 points (9.7% ROI). Directors should consider adding Crown Guard before Week 5.',
    fantasyMetrics: {
      topROI: { corps: 'Carolina Crown', caption: 'Guard', pointsGained: 2.9, roiPercent: 9.7 },
      buyLow: [{ corps: 'Boston Crusaders', reason: 'Percussion trending up, underowned', projectedGain: 1.5 }],
      sellHigh: [],
    },
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    trendingCorps: [
      { corps: 'Carolina Crown', direction: 'up', reason: 'Visual +0.45, new closer impact', weeklyChange: 0.45, fantasyValue: 'buy' },
    ],
  },
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

function formatTimeAgo(dateString) {
  const date = new Date(dateString);
  const now = new Date();
  const diffInMs = now - date;
  const diffInHours = Math.floor(diffInMs / (1000 * 60 * 60));
  const diffInDays = Math.floor(diffInHours / 24);

  if (diffInHours < 1) return 'Just now';
  if (diffInHours < 24) return `${diffInHours}h ago`;
  if (diffInDays === 1) return 'Yesterday';
  return `${diffInDays} days ago`;
}

function getCategoryConfig(category) {
  switch (category) {
    case 'dci':
      return {
        label: 'DCI RECAP',
        bgClass: 'bg-[#0057B8]',
        textClass: 'text-[#0057B8]',
        bgLightClass: 'bg-[#0057B8]/20',
        icon: Trophy,
      };
    case 'fantasy':
      return {
        label: 'FANTASY',
        bgClass: 'bg-orange-500',
        textClass: 'text-orange-400',
        bgLightClass: 'bg-orange-500/20',
        icon: Flame,
      };
    case 'analysis':
      return {
        label: 'ANALYSIS',
        bgClass: 'bg-purple-500',
        textClass: 'text-purple-400',
        bgLightClass: 'bg-purple-500/20',
        icon: Newspaper,
      };
    default:
      return {
        label: 'NEWS',
        bgClass: 'bg-gray-500',
        textClass: 'text-gray-400',
        bgLightClass: 'bg-gray-500/20',
        icon: Newspaper,
      };
  }
}

// =============================================================================
// SUB-COMPONENTS
// =============================================================================

function TrendingBadge({ direction }) {
  if (direction === 'up') {
    return <TrendingUp className="w-3 h-3 text-green-500" />;
  }
  if (direction === 'down') {
    return <TrendingDown className="w-3 h-3 text-red-500" />;
  }
  return <Minus className="w-3 h-3 text-gray-500" />;
}

function FantasyValueBadge({ value }) {
  const config = {
    buy: { label: 'BUY', bgClass: 'bg-green-500/20', textClass: 'text-green-400', icon: ArrowUpRight },
    sell: { label: 'SELL', bgClass: 'bg-red-500/20', textClass: 'text-red-400', icon: ArrowDownRight },
    hold: { label: 'HOLD', bgClass: 'bg-yellow-500/20', textClass: 'text-yellow-400', icon: Minus },
  };
  const { label, bgClass, textClass, icon: Icon } = config[value] || config.hold;

  return (
    <span className={`inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[10px] font-bold ${bgClass} ${textClass}`}>
      <Icon className="w-2.5 h-2.5" />
      {label}
    </span>
  );
}

function FantasyROIBadge({ metrics }) {
  if (!metrics?.topROI) return null;

  const { corps, caption, pointsGained, roiPercent } = metrics.topROI;
  const isPositive = roiPercent >= 0;

  return (
    <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-gradient-to-r from-green-500/20 to-emerald-500/10 border border-green-500/30 rounded-sm">
      <DollarSign className="w-4 h-4 text-green-400" />
      <div className="flex flex-col">
        <span className="text-[10px] text-green-400/80 uppercase tracking-wider font-medium">Top ROI</span>
        <span className="text-xs text-white font-bold">
          {corps} {caption}: <span className={isPositive ? 'text-green-400' : 'text-red-400'}>
            {isPositive ? '+' : ''}{pointsGained.toFixed(1)} pts ({roiPercent.toFixed(1)}%)
          </span>
        </span>
      </div>
    </div>
  );
}

function HeroStory({ story, onClick }) {
  const config = getCategoryConfig(story.category);
  const Icon = config.icon;

  return (
    <article
      className="mb-6 bg-[#1a1a1a] border border-[#333] rounded-sm overflow-hidden cursor-pointer hover:border-[#444] transition-colors"
      onClick={() => onClick?.(story)}
    >
      {/* Hero Image - Uses Cloudinary optimized URL or placeholder */}
      <div className="aspect-video bg-gradient-to-br from-[#0057B8]/20 to-[#1a1a1a] relative overflow-hidden">
        {story.imageUrl ? (
          <img
            src={story.imageUrl}
            alt={story.headline}
            className="w-full h-full object-cover"
            loading="eager"
          />
        ) : (
          <div className="absolute inset-0 flex items-center justify-center">
            <Icon className="w-16 h-16 text-[#0057B8]/40" />
          </div>
        )}
        {/* Gradient overlay for text readability */}
        <div className="absolute inset-0 bg-gradient-to-t from-[#1a1a1a] via-transparent to-transparent" />
      </div>

      {/* Hero Content */}
      <div className="p-4 lg:p-6">
        <div className="flex items-center gap-3 mb-3">
          <span className={`px-2 py-1 ${config.bgClass} text-white text-xs font-bold uppercase tracking-wider`}>
            {config.label}
          </span>
          <span className="flex items-center gap-1 text-xs text-gray-500">
            <Clock className="w-3 h-3" />
            {formatTimeAgo(story.createdAt)}
          </span>
        </div>

        <h1 className="text-xl lg:text-2xl xl:text-3xl font-black text-white leading-tight mb-3">
          {story.headline}
        </h1>

        <p className="text-base text-gray-400 leading-relaxed mb-4">
          {story.summary}
        </p>

        {/* Fantasy ROI Badge */}
        {story.fantasyMetrics && (
          <div className="mb-4">
            <FantasyROIBadge metrics={story.fantasyMetrics} />
          </div>
        )}

        {/* Fantasy Impact Highlight */}
        {story.fantasyImpact && (
          <div className="p-3 bg-orange-500/10 border border-orange-500/20 rounded-sm mb-4">
            <div className="flex items-center gap-2 mb-1">
              <Flame className="w-4 h-4 text-orange-400" />
              <span className="text-xs font-bold text-orange-400 uppercase">Fantasy Impact</span>
            </div>
            <p className="text-sm text-orange-100/80">{story.fantasyImpact}</p>
          </div>
        )}

        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 flex-wrap">
            {story.trendingCorps?.slice(0, 2).map((corp, idx) => (
              <span key={idx} className="flex items-center gap-1.5 text-xs text-gray-400">
                <TrendingBadge direction={corp.direction} />
                <span className="text-white">{corp.corps}</span>
                {corp.weeklyChange !== undefined && (
                  <span className={corp.weeklyChange >= 0 ? 'text-green-400' : 'text-red-400'}>
                    {corp.weeklyChange >= 0 ? '+' : ''}{corp.weeklyChange.toFixed(2)}
                  </span>
                )}
                {corp.fantasyValue && <FantasyValueBadge value={corp.fantasyValue} />}
              </span>
            ))}
          </div>
          <button className="flex items-center gap-1 text-[#0057B8] text-sm font-bold hover:text-[#0066d6] transition-colors">
            Read More
            <ChevronRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </article>
  );
}

function NewsCard({ story, onClick }) {
  const config = getCategoryConfig(story.category);
  const Icon = config.icon;
  const isFantasy = story.category === 'fantasy';

  return (
    <article
      className="bg-[#1a1a1a] border border-[#333] rounded-sm p-4 hover:border-[#444] transition-colors cursor-pointer"
      onClick={() => onClick?.(story)}
    >
      <div className="flex items-start gap-4">
        {/* Story Thumbnail */}
        <div className="hidden sm:flex flex-shrink-0 w-20 h-20 bg-[#222] border border-[#333] rounded-sm items-center justify-center">
          <Icon className={`w-8 h-8 ${isFantasy ? 'text-orange-500/50' : 'text-[#0057B8]/50'}`} />
        </div>

        {/* Story Content */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-2">
            <span className={`px-1.5 py-0.5 text-xs font-bold uppercase tracking-wider ${config.bgLightClass} ${config.textClass}`}>
              {config.label}
            </span>
            <span className="text-xs text-gray-600">{formatTimeAgo(story.createdAt)}</span>
          </div>

          <h2 className={`text-base lg:text-lg font-bold leading-snug mb-1 ${isFantasy ? 'text-orange-50' : 'text-white'}`}>
            {story.headline}
          </h2>

          <p className="text-sm text-gray-500 line-clamp-2">
            {story.summary}
          </p>

          {/* Fantasy ROI Badge (compact) */}
          {story.fantasyMetrics?.topROI && (
            <div className="mt-2 inline-flex items-center gap-1.5 px-2 py-1 bg-green-500/10 border border-green-500/20 rounded-sm">
              <DollarSign className="w-3 h-3 text-green-400" />
              <span className="text-[11px] text-green-400 font-semibold">
                {story.fantasyMetrics.topROI.corps}: +{story.fantasyMetrics.topROI.roiPercent.toFixed(1)}% ROI
              </span>
            </div>
          )}

          {/* Trending indicators */}
          {story.trendingCorps?.length > 0 && (
            <div className="flex items-center gap-3 mt-2 flex-wrap">
              {story.trendingCorps.slice(0, 2).map((corp, idx) => (
                <span key={idx} className="flex items-center gap-1 text-xs text-gray-500">
                  <TrendingBadge direction={corp.direction} />
                  <span className="text-gray-300">{corp.corps}</span>
                  {corp.fantasyValue && <FantasyValueBadge value={corp.fantasyValue} />}
                </span>
              ))}
            </div>
          )}
        </div>
      </div>
    </article>
  );
}

function LoadingState() {
  return (
    <div className="flex flex-col items-center justify-center py-12 text-gray-500">
      <Loader2 className="w-8 h-8 animate-spin mb-3" />
      <p className="text-sm">Loading news feed...</p>
    </div>
  );
}

function ErrorState({ onRetry }) {
  return (
    <div className="flex flex-col items-center justify-center py-12 text-gray-500">
      <AlertCircle className="w-8 h-8 mb-3 text-red-400" />
      <p className="text-sm mb-3">Unable to load news feed</p>
      <button
        onClick={onRetry}
        className="px-4 py-2 text-sm font-bold text-[#0057B8] border border-[#0057B8] rounded-sm hover:bg-[#0057B8]/10 transition-colors"
      >
        Try Again
      </button>
    </div>
  );
}

// =============================================================================
// MAIN COMPONENT
// =============================================================================

export default function NewsFeed({ onStoryClick, maxItems = 5 }) {
  const [news, setNews] = useState(FALLBACK_NEWS);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchNews = async () => {
    setLoading(true);
    setError(null);

    try {
      const result = await getRecentNews({ limit: maxItems + 1 }); // +1 for hero

      if (result.data?.success && result.data.news?.length > 0) {
        setNews(result.data.news);
      } else {
        // Use fallback data if no news available
        setNews(FALLBACK_NEWS);
      }
    } catch (err) {
      console.error('Error fetching news:', err);
      // Use fallback data on error
      setNews(FALLBACK_NEWS);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchNews();
  }, [maxItems]);

  const handleStoryClick = (story) => {
    onStoryClick?.(story);
  };

  if (loading && news.length === 0) {
    return <LoadingState />;
  }

  if (error && news.length === 0) {
    return <ErrorState onRetry={fetchNews} />;
  }

  const [heroStory, ...otherStories] = news;

  return (
    <div>
      {/* Section Header */}
      <div className="flex items-center gap-2 mb-4">
        <Newspaper className="w-5 h-5 text-[#0057B8]" />
        <span className="text-xs font-bold text-gray-500 uppercase tracking-widest">
          News & Analysis
        </span>
      </div>

      {/* Hero Story */}
      {heroStory && (
        <HeroStory story={heroStory} onClick={handleStoryClick} />
      )}

      {/* News Feed */}
      <div className="space-y-4">
        {otherStories.slice(0, maxItems - 1).map((story) => (
          <NewsCard key={story.id} story={story} onClick={handleStoryClick} />
        ))}
      </div>

      {/* Load More */}
      <div className="mt-6 text-center">
        <button className="px-6 py-3 border border-[#333] text-gray-400 text-sm font-bold uppercase tracking-wider hover:border-[#444] hover:text-white transition-all">
          Load More Stories
        </button>
      </div>
    </div>
  );
}

// =============================================================================
// FANTASY IMPACT WIDGET (Standalone for sidebar use)
// =============================================================================

export function FantasyImpactWidget({ news }) {
  // Get most recent fantasy impact
  const latestWithImpact = news?.find(n => n.fantasyImpact);

  if (!latestWithImpact) {
    return null;
  }

  const metrics = latestWithImpact.fantasyMetrics;

  return (
    <div className="bg-[#1a1a1a] border border-[#333] rounded-sm">
      {/* Header */}
      <div className="bg-[#222] px-3 py-2.5 border-b border-[#333] flex items-center justify-between">
        <h3 className="text-xs font-bold text-orange-400 uppercase tracking-wider flex items-center gap-2">
          <Flame className="w-3.5 h-3.5" />
          Fantasy Impact
        </h3>
        <span className="text-xs text-gray-500">Latest</span>
      </div>

      {/* Content */}
      <div className="p-3">
        {/* Top ROI Highlight */}
        {metrics?.topROI && (
          <div className="mb-3 p-2 bg-green-500/10 border border-green-500/20 rounded-sm">
            <div className="flex items-center gap-1.5 mb-1">
              <DollarSign className="w-3 h-3 text-green-400" />
              <span className="text-[10px] text-green-400 uppercase font-bold">Top ROI This Week</span>
            </div>
            <div className="text-sm text-white font-semibold">
              {metrics.topROI.corps} {metrics.topROI.caption}
            </div>
            <div className="text-xs text-green-400">
              +{metrics.topROI.pointsGained.toFixed(1)} pts ({metrics.topROI.roiPercent.toFixed(1)}% ROI)
            </div>
          </div>
        )}

        <p className="text-sm text-gray-300 leading-relaxed mb-3">
          {latestWithImpact.fantasyImpact}
        </p>

        {/* Buy Low Opportunities */}
        {metrics?.buyLow?.length > 0 && (
          <div className="mb-3">
            <div className="text-[10px] text-green-400 uppercase font-bold mb-1.5 flex items-center gap-1">
              <ArrowUpRight className="w-3 h-3" />
              Buy Low
            </div>
            {metrics.buyLow.slice(0, 2).map((item, idx) => (
              <div key={idx} className="flex items-center justify-between text-xs mb-1">
                <span className="text-white">{item.corps}</span>
                <span className="text-green-400">+{item.projectedGain.toFixed(1)} proj</span>
              </div>
            ))}
          </div>
        )}

        {/* Sell High Warnings */}
        {metrics?.sellHigh?.length > 0 && (
          <div className="mb-3">
            <div className="text-[10px] text-red-400 uppercase font-bold mb-1.5 flex items-center gap-1">
              <ArrowDownRight className="w-3 h-3" />
              Sell High
            </div>
            {metrics.sellHigh.slice(0, 2).map((item, idx) => (
              <div key={idx} className="flex items-center justify-between text-xs mb-1">
                <span className="text-white">{item.corps}</span>
                <span className={`${
                  item.riskLevel === 'high' ? 'text-red-400' :
                  item.riskLevel === 'medium' ? 'text-yellow-400' : 'text-gray-400'
                }`}>
                  {item.riskLevel} risk
                </span>
              </div>
            ))}
          </div>
        )}

        {/* Trending Corps */}
        {latestWithImpact.trendingCorps?.length > 0 && (
          <div className="pt-3 border-t border-[#333]/50">
            <div className="text-xs text-gray-500 uppercase mb-2">Trending Corps</div>
            <div className="space-y-1.5">
              {latestWithImpact.trendingCorps.slice(0, 3).map((corp, idx) => (
                <div key={idx} className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="text-sm text-white">{corp.corps}</span>
                    {corp.fantasyValue && <FantasyValueBadge value={corp.fantasyValue} />}
                  </div>
                  <span className={`flex items-center gap-1 text-xs ${
                    corp.direction === 'up' ? 'text-green-500' :
                    corp.direction === 'down' ? 'text-red-500' : 'text-gray-500'
                  }`}>
                    <TrendingBadge direction={corp.direction} />
                    {corp.weeklyChange !== undefined && (
                      <span>{corp.weeklyChange >= 0 ? '+' : ''}{corp.weeklyChange.toFixed(2)}</span>
                    )}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
