// Tests for sitemap URL extraction (helpers/scraping.js). dciFetch routes
// through a JS-rendering proxy, so a Yoast sitemap can come back as raw XML,
// as the browser XML-viewer's wrapped source, or as the XSLT-rendered HTML
// table (when the browser loads main-sitemap.xsl) — extraction must survive
// all three. The scrape canary's sitemap check calls discoverAllRecapUrls,
// which shares this parser, so these fixtures pin that contract too.

const { test, describe } = require("node:test");
const assert = require("node:assert/strict");

const { extractSitemapLocs, finalScoresToRecapUrl } = require("./scraping");

const RAW_XML_INDEX = `<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="//www.dci.org/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://www.dci.org/competition-sitemap.xml</loc>
    <lastmod>2026-07-26T04:06:23+00:00</lastmod>
  </sitemap>
  <sitemap>
    <loc>https://www.dci.org/competition-sitemap2.xml</loc>
    <lastmod>2026-07-26T04:06:23+00:00</lastmod>
  </sitemap>
  <sitemap>
    <loc>https://www.dci.org/event-sitemap.xml</loc>
    <lastmod>2026-07-26T16:57:08+00:00</lastmod>
  </sitemap>
</sitemapindex>`;

// Yoast's main-sitemap.xsl output: the URLs survive only as anchor hrefs, and
// the page carries an off-site "generated by Yoast SEO" credit link.
const RENDERED_HTML_SITEMAP = `<html xmlns="http://www.w3.org/1999/xhtml"><head>
<title>XML Sitemap</title></head><body>
<div id="sitemap__header"><h1>XML Sitemap</h1>
<p>This XML Sitemap is generated by <a href="https://yoa.st/1uo?utm_source=xml-sitemap">Yoast SEO</a>,
it is used by search engines like Google.</p></div>
<table id="sitemap" cellpadding="3">
  <thead><tr><th>URL</th><th>Images</th><th>Last Mod.</th></tr></thead>
  <tbody>
    <tr>
      <td><a href="https://www.dci.org/scores/final-scores/2026-dci-southwestern/">
        https://www.dci.org/scores/final-scores/2026-dci-southwestern/</a></td>
      <td>0</td><td>2026-07-20</td>
    </tr>
    <tr>
      <td><a href="https://www.dci.org/scores/final-scores/2026-dci-pittsburgh/">
        https://www.dci.org/scores/final-scores/2026-dci-pittsburgh/</a></td>
      <td>0</td><td>2026-07-21</td>
    </tr>
  </tbody>
</table></body></html>`;

// Chromium's XML viewer (when the stylesheet fails to load) keeps the original
// document — real <loc> elements included — inside a hidden source div.
const XML_VIEWER_WRAPPED = `<html><body>
<div id="webkit-xml-viewer-source-xml">
<sitemapindex><sitemap><loc>https://www.dci.org/competition-sitemap.xml</loc></sitemap></sitemapindex>
</div></body></html>`;

describe("extractSitemapLocs", () => {
  test("parses <loc> entries from raw sitemap XML", () => {
    assert.deepEqual(extractSitemapLocs(RAW_XML_INDEX), [
      "https://www.dci.org/competition-sitemap.xml",
      "https://www.dci.org/competition-sitemap2.xml",
      "https://www.dci.org/event-sitemap.xml",
    ]);
  });

  test("parses <loc> entries wrapped by the browser XML viewer", () => {
    assert.deepEqual(extractSitemapLocs(XML_VIEWER_WRAPPED), [
      "https://www.dci.org/competition-sitemap.xml",
    ]);
  });

  test("falls back to dci.org anchors on an XSL-rendered HTML sitemap", () => {
    assert.deepEqual(extractSitemapLocs(RENDERED_HTML_SITEMAP), [
      "https://www.dci.org/scores/final-scores/2026-dci-southwestern/",
      "https://www.dci.org/scores/final-scores/2026-dci-pittsburgh/",
    ]);
  });

  test("rendered-HTML fallback drops off-site links (Yoast credit)", () => {
    const urls = extractSitemapLocs(RENDERED_HTML_SITEMAP);
    assert.ok(urls.every((u) => /^https:\/\/www\.dci\.org\//.test(u)));
  });

  test("returns [] for a body with neither locs nor dci.org anchors", () => {
    assert.deepEqual(extractSitemapLocs("<html><body>Just a moment...</body></html>"), []);
  });

  test("rendered final-scores anchors still derive recap URLs", () => {
    const [first] = extractSitemapLocs(RENDERED_HTML_SITEMAP);
    assert.equal(
      finalScoresToRecapUrl(first),
      "https://www.dci.org/scores/recap/2026-dci-southwestern/"
    );
  });
});
