/**
 * Client-side venue helpers for the Host-a-Show picker (Schedule page).
 *
 * Mirrors the server's venue resolution (functions/src/helpers/podium/venues.js
 * + the committed gazetteer) using the slim client artifact generated by
 * functions/src/scripts/buildClientVenues.js. Directors book a show against a
 * KNOWN city instead of a free-text guess, and cities already on the season
 * schedule are resolved by venueId so the picker can rule them out — matching
 * the authoritative check in the hostEvent callable.
 */

import venueData from '../data/hostableVenues.json';

/** Distinct hostable cities, each with a "City, ST" display label. */
export const HOSTABLE_VENUES = venueData.venues.map((v) => ({
  ...v,
  label: `${v.city}, ${v.region}`,
}));

const KEY_TO_ID = venueData.keyToId;

/**
 * Canonical form of a raw location string — the gazetteer key. Kept byte-for-byte
 * in sync with normalizeKey in functions/src/helpers/podium/venues.js so client
 * and server resolve the same string to the same venue.
 * @param {string} raw
 * @returns {string}
 */
export function normalizeVenueKey(raw) {
  return String(raw || '')
    .toLowerCase()
    .replace(/[.]+/g, ' ')
    .replace(/[^a-z\s,'-]/g, ' ')
    .replace(/\s+/g, ' ')
    .replace(/\s*,\s*/g, ', ')
    .trim()
    .replace(/^,\s*/, '')
    .replace(/,\s*$/, '');
}

/**
 * Resolve a location string to a venueId, or null when it isn't a known city.
 * @param {string} locationString e.g. "Allentown, Pennsylvania"
 * @returns {string|null}
 */
export function resolveVenueId(locationString) {
  return KEY_TO_ID[normalizeVenueKey(locationString)] || null;
}

/**
 * The set of venueIds already claimed by shows on the schedule, so the picker
 * can exclude them (a city can host at most one show per season).
 * @param {Array<{location?: string}>} competitions schedule competitions/shows
 * @returns {Set<string>}
 */
export function scheduledVenueIds(competitions) {
  const taken = new Set();
  for (const comp of competitions || []) {
    const id = resolveVenueId(comp?.location);
    if (id) taken.add(id);
  }
  return taken;
}
