/**
 * Client-side venue helpers for the Host-a-Show picker (Schedule page).
 *
 * Mirrors the server's venue resolution (functions/src/helpers/podium/venues.js
 * + the committed gazetteer) using the slim client artifact generated by
 * functions/src/scripts/buildClientVenues.js. Directors book a show against a
 * KNOWN city instead of a free-text guess, and cities already on the season
 * schedule are resolved by venueId so the picker can rule them out — matching
 * the authoritative check in the hostEvent callable.
 *
 * Hometowns are NOT limited to these cities — the registration picker searches
 * every real US/Canadian town via utils/places.ts.
 */

import venueData from '../data/hostableVenues.json';

/** Distinct hostable cities, each with a "City, ST" display label. */
export const HOSTABLE_VENUES = venueData.venues.map((v) => ({
  ...v,
  label: `${v.city}, ${v.region}`,
}));

/** @type {Record<string, string>} */
const KEY_TO_ID = venueData.keyToId;

/**
 * Canonical form of a raw location string — the gazetteer key. Kept byte-for-byte
 * in sync with normalizeKey in functions/src/helpers/podium/venues.js so client
 * and server resolve the same string to the same venue.
 * @param {string|null|undefined} raw
 * @returns {string}
 */
export function normalizeVenueKey(raw) {
  return String(raw || '')
    .toLowerCase()
    .replace(/[.]+/g, ' ')
    .replace(/[^a-z\s,'-]/g, ' ')
    .replace(/\s+/g, ' ')
    .replace(/\s*,\s*/g, ', ')
    .trim()
    .replace(/^,\s*/, '')
    .replace(/,\s*$/, '');
}

/**
 * Resolve a location string to a venueId, or null when it isn't a known city.
 * @param {string|null|undefined} locationString e.g. "Allentown, Pennsylvania"
 * @returns {string|null}
 */
export function resolveVenueId(locationString) {
  return (
    KEY_TO_ID[normalizeVenueKey(locationString)] ||
    KEY_TO_ID[normalizeVenueKey(collapseMultiCity(locationString))] ||
    null
  );
}

/**
 * A multi-city show name collapsed to its last city — "Lexington/Winchester,
 * KY" → "Winchester, KY", the town the show is held in. Mirrors
 * collapseMultiCity in functions/src/helpers/locationFormat.js; a string with
 * no slash comes back unchanged.
 * @param {string|null|undefined} location
 * @returns {string}
 */
export function collapseMultiCity(location) {
  const text = String(location || '');
  const comma = text.indexOf(',');
  const cityPart = comma >= 0 ? text.slice(0, comma) : text;
  if (!cityPart.includes('/')) return text;
  const cities = cityPart
    .split('/')
    .map((s) => s.trim())
    .filter(Boolean);
  if (!cities.length) return text;
  return `${cities[cities.length - 1]}${comma >= 0 ? text.slice(comma) : ''}`;
}
